# Generated by Django 3.2.3 on 2021-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shorturl_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
